pub fn jobs() -> &'static [(fn(&str), &'static str, &'static str)] {
    &[
        (
            day_01::pt_1,
            "day_1_pt1",
            include_str!("../../day_01/input.txt"),
        ),
        (
            day_01::pt_2,
            "day_1_pt2",
            include_str!("../../day_01/input.txt"),
        ),
        (
            day_02::pt_1,
            "day_2_pt1",
            include_str!("../../day_02/input.txt"),
        ),
        (
            day_02::pt_2,
            "day_2_pt2",
            include_str!("../../day_02/input.txt"),
        ),
        (
            day_03::pt_1,
            "day_3_pt1",
            include_str!("../../day_03/input.txt"),
        ),
        (
            day_03::pt_2,
            "day_3_pt2",
            include_str!("../../day_03/input.txt"),
        ),
        (
            day_04::pt_1,
            "day_4_pt1",
            include_str!("../../day_04/input.txt"),
        ),
        (
            day_04::pt_2,
            "day_4_pt2",
            include_str!("../../day_04/input.txt"),
        ),
        (
            day_05::pt_1,
            "day_5_pt1",
            include_str!("../../day_05/input.txt"),
        ),
        (
            day_05::pt_2,
            "day_5_pt2",
            include_str!("../../day_05/input.txt"),
        ),
        (
            day_06::pt_1,
            "day_6_pt1",
            include_str!("../../day_06/input.txt"),
        ),
        (
            day_06::pt_2,
            "day_6_pt2",
            include_str!("../../day_06/input.txt"),
        ),
        (
            day_07::pt_1,
            "day_7_pt1",
            include_str!("../../day_07/input.txt"),
        ),
        (
            day_07::pt_2,
            "day_7_pt2",
            include_str!("../../day_07/input.txt"),
        ),
        (
            day_08::pt_1,
            "day_8_pt1",
            include_str!("../../day_08/input.txt"),
        ),
        (
            day_08::pt_2,
            "day_8_pt2",
            include_str!("../../day_08/input.txt"),
        ),
        (
            day_09::pt_1,
            "day_9_pt1",
            include_str!("../../day_09/input.txt"),
        ),
        (
            day_09::pt_2,
            "day_9_pt2",
            include_str!("../../day_09/input.txt"),
        ),
        (
            day_10::pt_1,
            "day_10_pt1",
            include_str!("../../day_10/input.txt"),
        ),
        (
            day_10::pt_2,
            "day_10_pt2",
            include_str!("../../day_10/input.txt"),
        ),
        (
            day_11::pt_1,
            "day_11_pt1",
            include_str!("../../day_11/input.txt"),
        ),
        (
            day_11::pt_2,
            "day_11_pt2",
            include_str!("../../day_11/input.txt"),
        ),
        (
            day_12::pt_1,
            "day_12_pt1",
            include_str!("../../day_12/input.txt"),
        ),
        (
            day_12::pt_2,
            "day_12_pt2",
            include_str!("../../day_12/input.txt"),
        ),
        (
            day_13::pt_1,
            "day_13_pt1",
            include_str!("../../day_13/input.txt"),
        ),
        (
            day_13::pt_2,
            "day_13_pt2",
            include_str!("../../day_13/input.txt"),
        ),
        (
            day_14::pt_1,
            "day_14_pt1",
            include_str!("../../day_14/input.txt"),
        ),
        (
            day_14::pt_2,
            "day_14_pt2",
            include_str!("../../day_14/input.txt"),
        ),
        (
            day_15::pt_1,
            "day_15_pt1",
            include_str!("../../day_15/input.txt"),
        ),
        (
            day_15::pt_2,
            "day_15_pt2",
            include_str!("../../day_15/input.txt"),
        ),
        (
            day_16::pt_1,
            "day_16_pt1",
            include_str!("../../day_16/input.txt"),
        ),
        (
            day_16::pt_2,
            "day_16_pt2",
            include_str!("../../day_16/input.txt"),
        ),
        (
            day_17::pt_1,
            "day_17_pt1",
            include_str!("../../day_17/input.txt"),
        ),
        (
            day_17::pt_2,
            "day_17_pt2",
            include_str!("../../day_17/input.txt"),
        ),
        (
            day_18::pt_1,
            "day_18_pt1",
            include_str!("../../day_18/input.txt"),
        ),
        (
            day_18::pt_2,
            "day_18_pt2",
            include_str!("../../day_18/input.txt"),
        ),
        (
            day_19::pt_1,
            "day_19_pt1",
            include_str!("../../day_19/input.txt"),
        ),
        (
            day_19::pt_2,
            "day_19_pt2",
            include_str!("../../day_19/input.txt"),
        ),
        (
            day_20::pt_1,
            "day_20_pt1",
            include_str!("../../day_20/input.txt"),
        ),
        (
            day_20::pt_2,
            "day_20_pt2",
            include_str!("../../day_20/input.txt"),
        ),
        (
            day_21::pt_1,
            "day_21_pt1",
            include_str!("../../day_21/input.txt"),
        ),
        (
            day_21::pt_2,
            "day_21_pt2",
            include_str!("../../day_21/input.txt"),
        ),
        (
            day_22::pt_1,
            "day_22_pt1",
            include_str!("../../day_22/input.txt"),
        ),
        (
            day_22::pt_2,
            "day_22_pt2",
            include_str!("../../day_22/input.txt"),
        ),
        (
            day_23::pt_1,
            "day_23_pt1",
            include_str!("../../day_23/input.txt"),
        ),
        (
            day_23::pt_2,
            "day_23_pt2",
            include_str!("../../day_23/input.txt"),
        ),
        (
            day_24::pt_1,
            "day_24_pt1",
            include_str!("../../day_24/input.txt"),
        ),
        (
            day_24::pt_2,
            "day_24_pt2",
            include_str!("../../day_24/input.txt"),
        ),
        (
            day_25::pt_1,
            "day_25_pt1",
            include_str!("../../day_25/input.txt"),
        ),
        (
            day_25::pt_2,
            "day_25_pt2",
            include_str!("../../day_25/input.txt"),
        ),
    ]
}
