pub fn jobs() -> &'static [(fn(), &'static str)] {
    &[
        (day_1::main, "day_1"),
        (day_2::main, "day_2"),
        (day_3::main, "day_3"),
        (day_4::main, "day_4"),
        (day_5::main, "day_5"),
        (day_6::main, "day_6"),
        (day_7::main, "day_7"),
        (day_8::main, "day_8"),
        (day_9::main, "day_9"),
        (day_10::main, "day_10"),
        (day_11::main, "day_11"),
        (day_12::main, "day_12"),
        (day_13::main, "day_13"),
        (day_14::main, "day_14"),
        (day_15::main, "day_15"),
        (day_16::main, "day_16"),
        (day_17::main, "day_17"),
        (day_18::main, "day_18"),
        (day_19::main, "day_19"),
        (day_20::main, "day_20"),
        (day_21::main, "day_21"),
        (day_22::main, "day_22"),
        (day_23::main, "day_23"),
        (day_24::main, "day_24"),
        (day_25::main, "day_25"),
    ]
}
